# Generated by Django 6.0 on 2026-01-06 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mark',
            new_name='ExamMark',
        ),
    ]
